// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: Copyright 2026 Paracosmos Studio Inc.

export interface Currency {
    value: string; // ISO 4217 code
    symbol: string;
    name: string;
}

export const CURRENCIES: Currency[] = [
    { value: "USD", symbol: "$", name: "US Dollar" },
    { value: "EUR", symbol: "€", name: "Euro" },
    { value: "GBP", symbol: "£", name: "British Pound" },
    { value: "JPY", symbol: "¥", name: "Japanese Yen" },
    { value: "CNY", symbol: "¥", name: "Chinese Yuan" },
    { value: "CAD", symbol: "$", name: "Canadian Dollar" },
    { value: "AUD", symbol: "$", name: "Australian Dollar" },
    { value: "NZD", symbol: "$", name: "New Zealand Dollar" },
    { value: "CHF", symbol: "CHF", name: "Swiss Franc" },
    { value: "SGD", symbol: "$", name: "Singapore Dollar" },
    { value: "HKD", symbol: "$", name: "Hong Kong Dollar" },
    { value: "TWD", symbol: "NT$", name: "Taiwan Dollar" },
    { value: "INR", symbol: "₹", name: "Indian Rupee" },
    { value: "KRW", symbol: "₩", name: "South Korean Won" },
    { value: "KPW", symbol: "₩", name: "North Korean Won" },
    { value: "PHP", symbol: "₱", name: "Philippine Peso" },
    { value: "VND", symbol: "₫", name: "Vietnamese Dong" },
    { value: "LAK", symbol: "₭", name: "Lao Kip" },
    { value: "BDT", symbol: "৳", name: "Bangladeshi Taka" },
    { value: "PKR", symbol: "₨", name: "Pakistani Rupee" },
    { value: "LKR", symbol: "Rs", name: "Sri Lankan Rupee" },
    { value: "NPR", symbol: "₨", name: "Nepalese Rupee" },
    { value: "THB", symbol: "฿", name: "Thai Baht" },
    { value: "KHR", symbol: "៛", name: "Cambodian Riel" },
    { value: "MNT", symbol: "₮", name: "Mongolian Tögrög" },
    { value: "MYR", symbol: "RM", name: "Malaysian Ringgit" },
    { value: "IDR", symbol: "Rp", name: "Indonesian Rupiah" },
    { value: "MMK", symbol: "K", name: "Myanmar Kyat" },
    { value: "BND", symbol: "$", name: "Brunei Dollar" },
    { value: "MOP", symbol: "MOP$", name: "Macanese Pataca" },
    { value: "MVR", symbol: "Rf", name: "Maldivian Rufiyaa" },
    { value: "BTN", symbol: "Nu.", name: "Bhutanese Ngultrum" },
    { value: "AFN", symbol: "؋", name: "Afghan Afghani" },
    { value: "KZT", symbol: "₸", name: "Kazakhstani Tenge" },
    { value: "UZS", symbol: "soʻm", name: "Uzbekistani Som" },
    { value: "KGS", symbol: "с", name: "Kyrgyzstani Som" },
    { value: "TJS", symbol: "ЅМ", name: "Tajikistani Somoni" },
    { value: "TMT", symbol: "m", name: "Turkmenistani Manat" },
    { value: "SAR", symbol: "﷼", name: "Saudi Riyal" },
    { value: "IRR", symbol: "﷼", name: "Iranian Rial" },
    { value: "QAR", symbol: "﷼", name: "Qatari Riyal" },
    { value: "OMR", symbol: "﷼", name: "Omani Rial" },
    { value: "YER", symbol: "﷼", name: "Yemeni Rial" },
    { value: "AED", symbol: "د.إ", name: "UAE Dirham" },
    { value: "KWD", symbol: "د.ك", name: "Kuwaiti Dinar" },
    { value: "BHD", symbol: ".د.ب", name: "Bahraini Dinar" },
    { value: "JOD", symbol: "د.ا", name: "Jordanian Dinar" },
    { value: "IQD", symbol: "ع.د", name: "Iraqi Dinar" },
    { value: "LBP", symbol: "ل.ل", name: "Lebanese Pound" },
    { value: "SYP", symbol: "£", name: "Syrian Pound" },
    { value: "ILS", symbol: "₪", name: "Israeli Shekel" },
    { value: "RUB", symbol: "₽", name: "Russian Ruble" },
    { value: "UAH", symbol: "₴", name: "Ukrainian Hryvnia" },
    { value: "TRY", symbol: "₺", name: "Turkish Lira" },
    { value: "GEL", symbol: "₾", name: "Georgian Lari" },
    { value: "AZN", symbol: "₼", name: "Azerbaijani Manat" },
    { value: "AMD", symbol: "֏", name: "Armenian Dram" },
    { value: "BYN", symbol: "Br", name: "Belarusian Ruble" },
    { value: "MDL", symbol: "L", name: "Moldovan Leu" },
    { value: "CZK", symbol: "Kč", name: "Czech Koruna" },
    { value: "PLN", symbol: "zł", name: "Polish Złoty" },
    { value: "HUF", symbol: "Ft", name: "Hungarian Forint" },
    { value: "RON", symbol: "lei", name: "Romanian Leu" },
    { value: "BGN", symbol: "лв", name: "Bulgarian Lev" },
    { value: "RSD", symbol: "дин.", name: "Serbian Dinar" },
    { value: "MKD", symbol: "ден", name: "Macedonian Denar" },
    { value: "ALL", symbol: "L", name: "Albanian Lek" },
    { value: "BAM", symbol: "KM", name: "Bosnia-Herzegovina Mark" },
    { value: "HRK", symbol: "kn", name: "Croatian Kuna" },
    { value: "DKK", symbol: "kr", name: "Danish Krone" },
    { value: "NOK", symbol: "kr", name: "Norwegian Krone" },
    { value: "SEK", symbol: "kr", name: "Swedish Krona" },
    { value: "ISK", symbol: "kr", name: "Icelandic Króna" },
    { value: "NGN", symbol: "₦", name: "Nigerian Naira" },
    { value: "GHS", symbol: "₵", name: "Ghanaian Cedi" },
    { value: "ZAR", symbol: "R", name: "South African Rand" },
    { value: "EGP", symbol: "£", name: "Egyptian Pound" },
    { value: "KES", symbol: "KSh", name: "Kenyan Shilling" },
    { value: "TZS", symbol: "TSh", name: "Tanzanian Shilling" },
    { value: "UGX", symbol: "USh", name: "Ugandan Shilling" },
    { value: "ETB", symbol: "Br", name: "Ethiopian Birr" },
    { value: "MAD", symbol: "د.م.", name: "Moroccan Dirham" },
    { value: "DZD", symbol: "د.ج", name: "Algerian Dinar" },
    { value: "TND", symbol: "د.ت", name: "Tunisian Dinar" },
    { value: "LYD", symbol: "ل.د", name: "Libyan Dinar" },
    { value: "SDG", symbol: "ج.س.", name: "Sudanese Pound" },
    { value: "XOF", symbol: "CFA", name: "West African CFA Franc" },
    { value: "XAF", symbol: "FCFA", name: "Central African CFA Franc" },
    { value: "RWF", symbol: "FRw", name: "Rwandan Franc" },
    { value: "BIF", symbol: "FBu", name: "Burundian Franc" },
    { value: "CDF", symbol: "FC", name: "Congolese Franc" },
    { value: "ZMW", symbol: "ZK", name: "Zambian Kwacha" },
    { value: "MWK", symbol: "MK", name: "Malawian Kwacha" },
    { value: "MZN", symbol: "MT", name: "Mozambican Metical" },
    { value: "BWP", symbol: "P", name: "Botswana Pula" },
    { value: "NAD", symbol: "$", name: "Namibian Dollar" },
    { value: "SZL", symbol: "L", name: "Eswatini Lilangeni" },
    { value: "LSL", symbol: "L", name: "Lesotho Loti" },
    { value: "MUR", symbol: "₨", name: "Mauritian Rupee" },
    { value: "SCR", symbol: "₨", name: "Seychellois Rupee" },
    { value: "MGA", symbol: "Ar", name: "Malagasy Ariary" },
    { value: "AOA", symbol: "Kz", name: "Angolan Kwanza" },
    { value: "GMD", symbol: "D", name: "Gambian Dalasi" },
    { value: "GNF", symbol: "FG", name: "Guinean Franc" },
    { value: "SLL", symbol: "Le", name: "Sierra Leonean Leone" },
    { value: "LRD", symbol: "$", name: "Liberian Dollar" },
    { value: "CVE", symbol: "$", name: "Cape Verdean Escudo" },
    { value: "MXN", symbol: "$", name: "Mexican Peso" },
    { value: "BRL", symbol: "R$", name: "Brazilian Real" },
    { value: "ARS", symbol: "$", name: "Argentine Peso" },
    { value: "CLP", symbol: "$", name: "Chilean Peso" },
    { value: "COP", symbol: "$", name: "Colombian Peso" },
    { value: "PEN", symbol: "S/", name: "Peruvian Sol" },
    { value: "UYU", symbol: "$U", name: "Uruguayan Peso" },
    { value: "PYG", symbol: "₲", name: "Paraguayan Guaraní" },
    { value: "BOB", symbol: "Bs.", name: "Bolivian Boliviano" },
    { value: "VES", symbol: "Bs.", name: "Venezuelan Bolívar" },
    { value: "GYD", symbol: "$", name: "Guyanese Dollar" },
    { value: "SRD", symbol: "$", name: "Surinamese Dollar" },
    { value: "CRC", symbol: "₡", name: "Costa Rican Colón" },
    { value: "GTQ", symbol: "Q", name: "Guatemalan Quetzal" },
    { value: "HNL", symbol: "L", name: "Honduran Lempira" },
    { value: "NIO", symbol: "C$", name: "Nicaraguan Córdoba" },
    { value: "PAB", symbol: "B/.", name: "Panamanian Balboa" },
    { value: "DOP", symbol: "RD$", name: "Dominican Peso" },
    { value: "CUP", symbol: "₱", name: "Cuban Peso" },
    { value: "HTG", symbol: "G", name: "Haitian Gourde" },
    { value: "JMD", symbol: "J$", name: "Jamaican Dollar" },
    { value: "TTD", symbol: "TT$", name: "Trinidad & Tobago Dollar" },
    { value: "BBD", symbol: "$", name: "Barbadian Dollar" },
    { value: "BSD", symbol: "$", name: "Bahamian Dollar" },
    { value: "BZD", symbol: "BZ$", name: "Belize Dollar" },
    { value: "XCD", symbol: "$", name: "East Caribbean Dollar" },
    { value: "FJD", symbol: "$", name: "Fijian Dollar" },
    { value: "PGK", symbol: "K", name: "Papua New Guinean Kina" },
    { value: "SBD", symbol: "$", name: "Solomon Islands Dollar" },
    { value: "VUV", symbol: "VT", name: "Vanuatu Vatu" },
    { value: "WST", symbol: "T", name: "Samoan Tala" },
    { value: "TOP", symbol: "T$", name: "Tongan Paʻanga" },
];

const SYMBOL_BY_CODE = new Map(CURRENCIES.map((c) => [c.value, c.symbol]));

/** Symbol for an ISO 4217 currency code, or null when blank/unknown. */
export function currencySymbol(code: string | null | undefined): string | null {
    return code ? SYMBOL_BY_CODE.get(code) ?? null : null;
}
