// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: Copyright 2026 Paracosmos Studio Inc.

import { getVersion } from "@tauri-apps/api/app";
import { invoke } from "@tauri-apps/api/core";

/**
 * Provenance line exporters embed in each format's native metadata channel:
 * "Generated by Tallier vX.Y.Z at YYYY-MM-dd HH:mm:ss UTC±HH:MM on <os> <os-version>"
 */
export type ExportStamp = string;

// local wall-clock as YYYY-MM-dd HH:mm:ss UTC±HH:MM
function timestamp(d: Date): string {
  const p = (n: number) => String(n).padStart(2, "0");
  const off = -d.getTimezoneOffset();
  const tz = `UTC${off < 0 ? "-" : "+"}${p(Math.floor(Math.abs(off) / 60))}:${p(Math.abs(off) % 60)}`;
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}:${p(d.getSeconds())} ${tz}`;
}

/**
 * App version from the tauri config plus the os name/version from the
 * `os_descriptor` command. Single source for app metadata.
 */
export async function appMeta(): Promise<{ version: string; os: string }> {
  const [version, os] = await Promise.all([getVersion(), invoke<string>("os_descriptor")]);
  return { version, os };
}

/**
 * Builds the provenance stamp burned into exported files for source tracking:
 * pdf document info/xmp, an html `generator` meta tag, a json field, and the
 * plain-text footer. CSV stays unstamped: it has no metadata layer, and a
 * comment row would break strict parsers.
 */
export async function buildExportStamp(): Promise<ExportStamp> {
  const { version, os } = await appMeta();
  return `Generated by Tallier v${version} at ${timestamp(new Date())} on ${os}`;
}
