import { getVersion } from "@tauri-apps/api/app";
import { invoke } from "@tauri-apps/api/core";

/** Provenance stamp exporters embed in each format's native metadata channel. */
export interface ExportStamp {
  /** "generated by Tallier vX.Y.Z at YYYY-MM-dd HH:mm:ss UTC±HH:MM on <os> <os-version>" */
  generated: string;
  /** Open-source support line carrying the project url. */
  support: string;
}

const SUPPORT = "help us keep it open-source at https://tallier.app/support";

// local wall-clock as YYYY-MM-dd HH:mm:ss UTC±HH:MM
function timestamp(d: Date): string {
  const p = (n: number) => String(n).padStart(2, "0");
  const off = -d.getTimezoneOffset();
  const tz = `UTC${off < 0 ? "-" : "+"}${p(Math.floor(Math.abs(off) / 60))}:${p(Math.abs(off) % 60)}`;
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}:${p(d.getSeconds())} ${tz}`;
}

/**
 * Builds the provenance stamp burned into exported files for source tracking:
 * pdf document info/xmp, an html `generator` meta tag, json fields, and the
 * plain-text footer. App version comes from the tauri config; the os
 * name/version from the `os_descriptor` command. CSV stays unstamped: it has
 * no metadata layer, and a comment row would break strict parsers.
 */
export async function buildExportStamp(): Promise<ExportStamp> {
  const [version, os] = await Promise.all([getVersion(), invoke<string>("os_descriptor")]);
  return {
    generated: `generated by Tallier v${version} at ${timestamp(new Date())} on ${os}`,
    support: SUPPORT,
  };
}
